### ISSUE TITLE
What is the MAX_OUTPUT_BBOX_COUNT value?

### ISSUE THREAD

**Issue by ViktorYastrebov** [wang-xinyu/tensorrtx#132]
Hello. It's really amazing work but I would like to ask 1 questions. As far as I know the yoloV3-SPP has the 1x3x80x80x85 + 1x3x40x40x85 + 1x3x20x20x85 output shapes under the original model.  Default value currently equals to 1000. This limit slices some detections so could you please give some info about it or some advice ?

**Comment by wang-xinyu** [comment]
The final layer in this yolov3-spp tensorrt implementation is a yolo plugin. which equals to the three yolo layers in pytorch.

It outputs the final results, including bboxes, class id and confidence.

The `MAX_OUTPUT_BBOX_COUNT` limits the max output bboxes. 1000 be default.   Because usually we don't have that many objects in one image.   While output size getting smaller, it will save the memcpy time.

**Comment by ViktorYastrebov** [comment]
Ok. Thank you for the information. I got the idea :)
