### ISSUE TITLE
Retinaface inference speed 

### ISSUE THREAD

**Issue by daiisuke27** [wang-xinyu/tensorrtx#229]
Hello ! Thank you for great work !

When using your retinaface [script](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface), i tested the inference with `./retina_r50 -d `, the inference time is too long : i am getting aroud 170ms for one image.
I wanted to know is it normal and what speed are you getting ??

Thank you !

**Comment by hailcpy** [comment]
hey could you check for multiple images, The inference time is high for first image but very low after that. I got 65fps on jetson Nano using the arcface tensorrt implementation and using Tensorrt python api for inferencing. Thanks @wang-xinyu  for your work. Earlier i was getting around 10fps. I am using it for face recognition with mtcnn tensorrt implementation by jk_jung which also gave an improvement of 4-5 times.

**Comment by daiisuke27** [comment]
@hailcpy 
Thank you so much ! this was my mistake, i was testing inference with only one image ! 
Could you share you python inference code for retinaface tensorrt ?
Thank you in advance !

**Comment by hailcpy** [comment]
@daiisuke27  glad i was of help. I have essentially replicated the python inference file in yolov5. There isn't much to change. You can do the same. I am attaching it here. There is one problem with the file. If you try to store the outputs for each image in a list or a variable it is somehow overwrited by the the latest output. So i have added some code in post process function which stores the embeddings from the arcface in a .npy file. Then i use another script to check the similarity scores. In my face recognition code this problem wasn't there maybe because i was getting and using embeddings in real time. If you face any problem feel free to ping.
https://drive.google.com/file/d/1v_1WdNad2_olQbOS6Q4TqJg60dyuDfK_/view?usp=sharing Here you can download it.

**Comment by daiisuke27** [comment]
Thank you for your help, i found out that i was doing a wrong reshape of the input (RetinaFace different than YOLO), now i am facing the same problem you mentioned.
I tried to put the loop inside the infer function with a list of images to detect, in the beginning i get correct outputs but at some point the output becomes the same for all inputs until the loop ends.
Another question, have you tried to use multi batch ? i tried to and got similar error.

**Comment by thimabru1010** [comment]
> hey could you check for multiple images, The inference time is high for first image but very low after that. I got 65fps on jetson Nano using the arcface tensorrt implementation and using Tensorrt python api for inferencing. Thanks @wang-xinyu for your work. Earlier i was getting around 10fps. I am using it for face recognition with mtcnn tensorrt implementation by jk_jung which also gave an improvement of 4-5 times.

When you set the Batch_size > 1, its clear the improvement speed. But how do I actually measure only the speed inference after the " warm-up"? The function doInference always instantiates for the first time the network. I couldn't modify doInference to separate inferences.

**Comment by thimabru1010** [comment]
I mean. If I want to use this in production, like a real-time inference in video I cannot stack all frames in a batch because I don't have all of them yet. In this context, How do I keep the network instantiated and do the inference with the network already warmed-up ?

**Comment by hailcpy** [comment]
No i wasn't using batch of images. I sent one image for inference, got the predictions and inference time. After that i sent another images and got the predictions and inference time. I have written python inference code which is used with real-time video feed and got around 60fps.

**Comment by leviethung2103** [comment]
> No i wasn't using batch of images. I sent one image for inference, got the predictions and inference time. After that i sent another images and got the predictions and inference time. I have written python inference code which is used with real-time video feed and got around 60fps.
@hailcpy 
Could I ask you a question? You mentioned that you got 65 FPS of Retina Net or ArcFace. Correct me if I was wrong. Currently, I've tried the MTCNN and it only reaches to 12 FPS with Webcam camera. How can you achieve a better FPS? Thank you

**Comment by aditya-jindal-trysolvio** [comment]
@leviethung2103  with MTCNN it is the same for me too i think. i used jk-jung's implementation. It was around 20-30 fps i think. don't remember sorry. But it was lower than arcface
.

**Comment by aditya-jindal-trysolvio** [comment]
this my second account btw @leviethung2103 , aside from hailcpy

**Comment by leviethung2103** [comment]
@aditya-jindal-trysolvio Hi hailcpy, thank you so much for your replying. I've tried the ArcFace on Jetson Nano and I couldn't achieve the good speed as yours. I am wondering that  have you apply any tricks on that? Thank you so much.

**Comment by aditya-jindal-trysolvio** [comment]
i am not sure, what fps are u getting. the 65 fps is for directly using a resized image for tensorrt. If u are using a camera feed and using opencv2 for resizing, rotating  img then it will have a huge hit on fps, you can see maybe 35-40fps. I can't say about the fps in my video feed since i was using it with mtcnn. Can u try 2 resized image on the inference code directly and check the time taken for the second image. it should be around 15ms.
