### ISSUE TITLE
batch_size and the inference time

### ISSUE THREAD

**Issue by passion3394** [wang-xinyu/tensorrtx#24]
thanks for your great repo!!
Now I want to do inference on Xavier. 
The origin batch_size is 1, the inference time is 24ms; 
If I change batch_size to 3, the inference time is about 67ms.

This is not what I want, I want to use more memory to exchange time: change batch_size to 3, and the inference time is about 24ms, GPU memory 3X. How should I do?

**Comment by wang-xinyu** [comment]
@passion3394 

I think it impossible that batch=3 can get same latency as batch=1. Because it needs more computation. When using multi batch, the overall FPS will increase a little, 
I made a multi batch test for yolov4,
you can refer to this comment https://github.com/AlexeyAB/darknet/pull/5453#issuecomment-624116856

**Comment by passion3394** [comment]
thanks for your reply, have you planned to implement EfficientDet serials?

**Comment by wang-xinyu** [comment]
I heard EfficientDet is hard to train, and hard to reach the same mAP as the paper, is it?

Do you know which repo provides trained model, and did you test it? how's the performance?

**Comment by passion3394** [comment]
I have trained EfficientDet d0 and d5 on my custom dataset, the training process is ok, but I haven't trained the EfficientDet on Coco. 
 I follow this repo https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch 

this repo seems good. It provides some pretrained pth files on coco.
