### ISSUE TITLE
 model zoo?

### ISSUE THREAD

**Issue by mosheliv** [wang-xinyu/tensorrtx#252]
Thank you for this repository. Is there a reason why the models are not provided as .wts? are they being adjusted to the current architecture? Or is it legal issues?

**Comment by wang-xinyu** [comment]
For each network, I provided a link of pytorch/mxnet implementation, from where you can download the pytorch/mxnet pretrained model.
The use the gen_wts.py provided in this repo to generate .wts.

You would better to go through the path from pytorch model to .wts, then tensorrt model. Because in this way, you can train your own model.

**Comment by mosheliv** [comment]
True, but it would be nice, just to allow people to check performance for
example, to provide the wts. I have spent a few days now getting pytorch
etc working on my nano just to find yolov4 is very slow (almost 1s). I am
not complaining, this is still great, but just saying it will help people
quickly check if tensortx suits thier needs.

Thank you!

**Comment by wang-xinyu** [comment]
Yes, you are right. I'll consider it.

**Comment by wang-xinyu** [comment]
.wts is portable. you should run pytorch on your PC, then run tensorrt serialization and inference on nano.

**Comment by wang-xinyu** [comment]
model zoo added https://github.com/wang-xinyu/tensorrtx/commit/0a45f3cf6df918bb06d973e54b4e53c66b1fb355

**Comment by mosheliv** [comment]
apologies, just got back to this. unfortunately, I can't download from baidu. would you consider putting the zoo on google drive or github?
