### ISSUE TITLE
No module named tensorrt

### ISSUE THREAD

**Issue by BLOO69** [wang-xinyu/tensorrtx#344]
```
Traceback (most recent call last):
  File "yolov5_trt.py", line 17, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'

```
I followed the instructions on https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5. Ran into this error at step 4. Would appreciate any help! Thanks!

**Comment by jovenwayfarer** [comment]
@BLOO69 hi, have you solved the issue? I installed tensorrt for python via pip3 install tensorrt, it was installed correctly, however I still have an error ```ModuleNotFoundError: No module named 'tensorrt'```. Thanks!

**Comment by waseemshahwan** [comment]
Was this issue investigated at all?

Using the docker image provided, I am able to build with all dependencies fine but python isn't finding tensorrt.

I've tried `pip3 install nvidia-pyindex && pip3 install nvidia-tensorrt` which seems to install for tensorrt 8
I've tried `apt-get install python3-libnvinfer-dev` which is also trying to update tensorrt to 8.

After these methods, yolov5_trt.py returns this error:
```
INTERNAL ERROR: [runtime.cpp::isCudaInstalledCorrectly::39] Error Code 6: Internal Error (CUDA initialization failure with error 3. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)
Traceback (most recent call last):
  File "yolov5_trt.py", line 365, in <module>
    yolov5_wrapper = YoLov5TRT(engine_file_path)
  File "yolov5_trt.py", line 83, in __init__
    runtime = trt.Runtime(TRT_LOGGER)
TypeError: pybind11::init(): factory function returned nullptr
```
which im guessing is because of wrong python trt version.

Cannot figure out how to get python to recognize current trt version.

thanks

**Comment by wang-xinyu** [comment]
@waseemshahwan seems CUDA is not properly installed. trt depends on cuda, and cuda version and trt version must match.
