### ISSUE TITLE
yolov5 int8 error

### ISSUE THREAD

**Issue by 992355092** [wang-xinyu/tensorrtx#352]
您好，我把yolov3中的calibrator.cpp和calibrator.h两个文件复制到yolov5工程下对yolov5s进行量化，能生成量化校准表，但是在推理的时候结果全都是0，无法检出目标，请问yolov5使用yolov3中的calibrator.cpp是不是要修改哪些地方？

**Comment by wang-xinyu** [comment]
I also tried yolov5 v3.0 int8, but failed with trt7.1+, cannot detect any objs.   While trt7.0 works well.

So you can try trt7.0.

**Comment by 992355092** [comment]
> I also tried yolov5 v3.0 int8, but failed with trt7.1+, cannot detect any objs. While trt7.0 works well.
> 
> So you can try trt7.0.

好的，我换个版本试试，但是不需要修改yolov3中的calibrator.cpp吗

**Comment by wang-xinyu** [comment]
不需要改，因为预处理都是一样的

**Comment by wang-xinyu** [comment]
另外可以试试我刚更新的yolov5 v4.0

**Comment by 992355092** [comment]
> 另外可以试试我刚更新的yolov5 v4.0

感谢大佬，今天测试了一下，在tensorrt7.0中可以正常的量化推理，结果也是对的。就是在7.2中有异常，不知道为啥

**Comment by BLOO69** [comment]
Could i ask what changes are to be made? I placed the 2 files in the yolov5 folder and #included both files in yolov5.cpp. I also added this block of code in yolov5.cpp. I also added my own dataset and placed it in build folder and renamed "coco_calib".
Thank You!

#elif defined(USE_INT8)
    std::cout << "Your platform support int8: " << (builder->platformHasFastInt8() ? "true" : "false") << std::endl;
    assert(builder->platformHasFastInt8());
    config->setFlag(BuilderFlag::kINT8);
    Int8EntropyCalibrator2 *calibrator = new Int8EntropyCalibrator2(1, INPUT_W, INPUT_H, "./coco_calib/", "int8calib.table", INPUT_BLOB_NAME);
    config->setInt8Calibrator(calibrator);

### Error
[ 50%] Built target myplugins
Scanning dependencies of target yolov5
[ 75%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
In file included from /home/student/yolov5-tensorrt/tensorrtx/yolov5/yolov5.cpp:7:0:
/home/student/yolov5-tensorrt/tensorrtx/yolov5/calibrator.cpp: In member function ‘virtual bool Int8EntropyCalibrator2::getBatch(void**, const char**, int)’:
/home/student/yolov5-tensorrt/tensorrtx/yolov5/calibrator.cpp:48:65: error: too many arguments to function ‘cv::Mat preprocess_img(cv::Mat&)’
         cv::Mat pr_img = preprocess_img(temp, input_w_, input_h_);
                                                                 ^
compilation terminated due to -Wfatal-errors.
CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/yolov5.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/yolov5.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xyt2008** [comment]
nvidia jetson xavier 要如何安装 tensorrt7.0？通过sdkmanager 下载里面的都是tensorrt7.1。

**Comment by xyt2008** [comment]
现在载nvidia jetson xavier上生成yolov5s的模型，fp16的精度都正常，检测结果没有问题。int8生成的框就很多问题。如何讲tensorrt版本到7.0？
