### ISSUE TITLE
Retinaface implementation question(based on Res50 backbone)

### ISSUE THREAD

**Issue by ViktorYastrebov** [wang-xinyu/tensorrtx#421]
Hello. I just would like to get a hint about the following statement
Under the TensoRT implementation there is a big difference in detections relate to the original Pytorch implementation
Does it relate to the ouput conversion ? 
I tried without confidence threshoulding of 0.1 
Could you provide the briefly explonation? I did not check all layers implementation yet

**Comment by wang-xinyu** [comment]
Hi @ViktorYastrebov , cannot understand what you were saying. Where did you find the statement?

**Comment by mfoglio** [comment]
Hi @wang-xinyu , as you can see I am really trying to dive into your TensorRT implementation. Thanks for the work and the support, I really appreciate it.

As @ViktorYastrebov said, I noticed an evident difference in the quality detection of your TensorRT implementation with respect to the PyTorch one, using the same weights. 

Is there any difference between the PyTorch and the TensorRT implementations, besides the resolution?

**Comment by mfoglio** [comment]
Specifically, it looks like the TensorRT implementation is detecting the same object many times with bounding boxes of different sizes. For instance, if there is a bus, you will have two bounding boxes, one perfect and the other one too big (like if you increased the size of the other one). However, I guess that these boxes are not deleted by the NMS because, since one is way big than the other, their IoU is not too big. The problem is that often the bigger box has greater accuracy. This does not happen in the PyTorch implementation for the same IoU and confidence threshold.

**Comment by ViktorYastrebov** [comment]
Hello. My point was: in some cases it's working worse for detecting small faces( specially quite far from the camera point).

**Comment by wang-xinyu** [comment]
did you try fp32?     int8 should have bad performance for small object.

**Comment by ViktorYastrebov** [comment]
Yeah. I used the fp32 and checked under world-largest-selfy. On that particular data it is almost the same. But on my video i can observe the significant difference.
Ok. I think we can postponed an issue. I have ported to ONNX (without gather op) and going to check
