### ISSUE TITLE
How to change tensorrt container version?

### ISSUE THREAD

**Issue by SinVl** [wang-xinyu/tensorrtx#533]
I built the yolov5s model according to your tutorial and tried to run it on triton inference service, but got an error like
```
E0509 10:48:33.958262 1 logging.cc:43] coreReadArchive.cpp (41) - Serialization Error in verifyHeader: 0 (Version tag does not match. Note: Current Version: 96, Serialized Engine Version: 89)
E0509 10:48:33.963258 1 logging.cc:43] INVALID_STATE: std::exception
E0509 10:48:33.963271 1 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
E0509 10:48:33.964105 1 model_repository_manager.cc:986] failed to load 'yolo_trt' version 1: Internal: unable to create TensorRT engine
```
My triton version is nvcr.io/nvidia/tritonserver:20.11-py3. How can I build yolov5 model in docker on container version nvcr.io/nvidia/tensorrt:20.11-py3? Now there is no way to configure it.

## Env

- GPU: T4
- OS: Ubuntu18.04
- Cuda: 9.1

**Comment by makaveli10** [comment]
The problem is the tensorrt engine is built on a different tensorrt version (89) and your are trying to make inference using that engine on different tesnorrt version (96).
So, the point being make sure you use the same version in both cases building the engine and running inference. Just check the trt version of triton inference server and build the engine on the same.

**Comment by SinVl** [comment]
@makaveli10 
Yes you are right. I use the Dockerfile of this repository to build the model, but I do not see which version of the NGC container it is based on, so I can change it to the one I need. Can I do this in a simple way, or do I have to use the image that is there and change the version of tensorrt already inside it?
