### ISSUE TITLE
About inference size

### ISSUE THREAD

**Issue by kundebuxing** [wang-xinyu/tensorrtx#596]
## Env
- GPU, e.g. RTX2080ti- OS, Win10, etc.- Cuda version10.1- TensorRT version6
## About this repo yolov5 5.0
My original size of training dataset is [640,640]
I generated yolov5.exe and yolov5.engine and can detect images and videos  with high efficiency.
However, when I try to change the value of INPUT_H and INPUT_W (yololater.h) to other value not 640 but multiple of 32(eg. 1024 or 8000 or 608 ) and generate new engine. The inference process can detect nothing.
How to modify the program to detect objects in large size of videos(eg 8000x1024)?
thank you for you reply!

**Comment by wang-xinyu** [comment]
You need rebuild everything after changing input size.

**Comment by kundebuxing** [comment]
thank you for your reply!
I rebuild every step. It works. But meet another problem.
My INPUT_H is 8000 and INPUT_W is 1024. 
When the test image is 8000x1000,it cannot detect all the objects in image. However, when i cut the 8000x1000 into two 4000x1000 images, it can detect all the objects.
So,why this happen? I have already changed the INPUT_H and INPUT_W to the same size as detected image.but it seems fail to detect the whole size of the images.

**Comment by kundebuxing** [comment]
> You need rebuild everything after changing input size.

thank you for your reply!
I rebuild every step. It works. But meet another problem.
My INPUT_H is 8000 and INPUT_W is 1024.
When the test image is 8000x1000,it cannot detect all the objects in image. However, when i cut the 8000x1000 into two 4000x1000 images, it can detect all the objects.
So,why this happen? I have already changed the INPUT_H and INPUT_W to the same size as detected image.but it seems fail to detect the whole size of the images.

**Comment by wang-xinyu** [comment]
You only need to change INPUT W&H once, before building, when doing inference, it will resize and pad your input image to the target size.

**Comment by kundebuxing** [comment]
> You only need to change INPUT W&H once
I only changed INPUT W&H in yololayer.h once.And the build engine and run inference.
The results is not good. It cannot detect objects in 8000x1024 but can detect the same obejects in small size image 2000x1024.

**Comment by kundebuxing** [comment]
> You only need to change INPUT W&H once, before building, when doing inference, it will resize and pad your input image to the target size.

You only need to change INPUT W&H once
I only changed INPUT W&H in yololayer.h once.And the build engine and run inference.
The results is not good. It cannot detect objects in 8000x1024 but can detect the same obejects in small size image 2000x1024.

**Comment by wang-xinyu** [comment]
Can you try 8000x1024 in pytorch side?

**Comment by kundebuxing** [comment]
> Can you try 8000x1024 in pytorch side?

Yes. very slow. But can detct all the objects.

**Comment by wang-xinyu** [comment]
Im not sure 8000 is too large for tensorrt.

**Comment by kundebuxing** [comment]
> Im not sure whether 8000 is too large for tensorrt.

thanks!
How can tensorrt detect two videos simultaneously?

**Comment by KevS272** [comment]
Hi guys,

I have a related question (not a problem or anything, that's why I don't want to create a new issue):

How would changing the INPUT_W&H the NNs capabilitiy to detect objects?

An example:
My yolov5s is trained with an image size of 640p (standard setting). I also create the engine with INPUT_W&H set to 640p. However, the images being fed into my inference script are in 1280x720p, so they get downscaled to 640x640p.

Would the detection performance benefit from increasing the INPUT_W&H to 720x720p (or even 1280x720p) because details in the image won't get lost in the downscaling or would it maybe decrease detection performance bc the net is used to get 640p images because it was trained this way?
Of course I could ramp up the training img size, the question remains, how would a NN trained on square images perform on non-square (eg 1280x720p) images?

At the moment I am trying to find the sweet spot between network architecture (s,m,l, ...) and input image size, balancing FPS requirements and the highest possible detection range. A better understanding of how the input sizes affect performance would avoid a lot of training and trying, so I would really appreciate knowing your opinion on this :) 

Thx and BR
Kevin

**Comment by wang-xinyu** [comment]
Usually, it's better to use same input dims for training and inferencing.
