### ISSUE TITLE
Yolov5 new model updates (verification with repo) 

### ISSUE THREAD

**Issue by marvision-ai** [wang-xinyu/tensorrtx#62]
The models have been updated on GDrive. I cant test it at the moment.. but I ask if someone can confirm if the changes still work with the repo?

I want to ask this now before many people run into the same issue (since they are all training with the newer models)
Link to new models: https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J

Yolov5s is only needed for testing. 

Thank you!

**Comment by wang-xinyu** [comment]
You can try it. I also updated the yolov5-s model on 23 June.

If the model from https://github.com/ultralytics/yolov5 not working,   I also made a copy of [yolov5s.pt(google drive)](https://drive.google.com/file/d/1w38DgmrP3iwiJi_AOdabuuE_zanMhO5_/view?usp=sharing). Just in case the yolov5 model updated.

**Comment by AleBasso80** [comment]
What do I have to modify in the source code to run yolov5 models different than s?

Thank you.

**Comment by wang-xinyu** [comment]
@AleBasso80 You need adapt the createEngine() in yolov5s.cpp.

**Comment by AleBasso80** [comment]
@wang-xinyu Thanks!

**Comment by AleBasso80** [comment]
@wang-xinyu : I realized that the yolov5 yaml models are identical and only the layer sizes differ, therefore I accordingly modified only the sizes in createEngine(), as you suggested. The changes should be correct, as I'm able to build and deploy the different engines, however I get no detection, whilst when I use your s model everything is fine. I studied your code, but I didn't find any place where I should modify something in order to get the system work. Am I missing something or perhaps may the ultralytics official weights differ from what you require?
Thank you.

**Comment by wang-xinyu** [comment]
@AleBasso80 There is a debug method. For example you set the conv layer before yololayer as the output,   build the engine, and run inference. Then compare the output with pytorch's same layer's output.    Or you can set whichever layer as output and compare. To see if the output is same as pytorch. Then find where the problem is.
