### ISSUE TITLE
engine built on 2080 won't work on 3070Ti

### ISSUE THREAD

**Issue by shyn** [wang-xinyu/tensorrtx#811]
## Env

- GPU: 2080 and 3070Ti
- OS: Windows 10
- Cuda: 11.1 
- TensorRT version: 7.2.3.4

## About this repo

- which branch/tag/commit are you using? yolov5-v5.0
- which model? yolov5

## Your problem

I have built the exe and dll on 2080 machine. Serialized an engine file.  It ran perfectly.
So I deployed all of this to 3070Ti **with the same versions of cuda and tensorrt** installed. Inference crashed with the engine from 2080.
It worked after reserializing a new engine file on 3070Ti.
I expect that I can just use the engine from 2080. (3070 Ti machines belong to our clients)

**Comment by KevS272** [comment]
Hi shyn,

the whole point of TensorRT is the optimization of the NN for the individual GPU it runs on. The optimization steps are therefore specific to the GPU you are running the serialization. That's why your engine won't run on another GPU especially not a GPU from a newer architecture.

So: You have to run the serialization on the target hardware (maybe it's possible to run serialization on one system using a 3070Ti for example and port the engine to other systems runnning a 3070Ti ... never tested something like that though)

BR

**Comment by shyn** [comment]
Fine. I thought so. If there is no other workaround, we will just do it on 3070Ti. Thx anyway!
